abc_course:
    resource: "@ABCCourseBundle/Resources/config/routing.yml"
    prefix:   /

abc_application:
    resource: "@ABCApplicationBundle/Resources/config/routing.yml"
    prefix:   /

abc_resource_person:
    resource: "@ABCResourcePersonBundle/Resources/config/routing.yml"
    prefix:   /

abc_login:
    resource: "@ABCLoginBundle/Resources/config/routing.yml"
    prefix:   /
