abc_resource_person_homepage:
    pattern:  /
    defaults: { _controller: ABCResourcePersonBundle:Default:index }
    
rsp_new:
    pattern: /new
    defaults: { _controller: ABCResourcePersonBundle:Resourceperson:new}

rsp_create:
    pattern: /new/create
    defaults: { _controller: ABCResourcePersonBundle:Resourceperson:create}